export type Domain = 'physical' | 'mental' | 'spiritual' | 'creative'
export type Volume = 'micro' | 'short' | 'medium' | 'long'

export interface Practice {
  id: string
  name: string
  cue: string           // one evocative sentence — not instructions
  domain: Domain
  volume: Volume
  durationSeconds: number
  reflectionPrompt: string
  tags: string[]        // for personalization matching
}

export const practices: Practice[] = [

  // ─── PHYSICAL ───────────────────────────────────────────────────────────────

  {
    id: 'spine-wave',
    name: 'Spine Wave',
    cue: 'Let the movement start from the base and find its way up — no rush, no destination.',
    domain: 'physical',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'Where did it want to go?',
    tags: ['mobility', 'warm-up', 'morning', 'floor'],
  },
  {
    id: 'squat-reach-flow',
    name: 'Squat & Reach Flow',
    cue: 'Find the bottom. Then reach from there — up, sideways, behind you. Explore the edges.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'What did your hips allow today?',
    tags: ['mobility', 'squat', 'morning', 'foundational'],
  },
  {
    id: 'locomotion-crawl',
    name: 'Locomotion Crawl',
    cue: 'Travel the floor. Change levels. Don\'t plan — let the next move come from where you are.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What pattern kept returning?',
    tags: ['locomotion', 'floor', 'play', 'coordination'],
  },
  {
    id: 'floor-flow',
    name: 'Floor Flow',
    cue: 'Stay low. Treat the floor as your partner. No hurry to stand.',
    domain: 'physical',
    volume: 'medium',
    durationSeconds: 600,
    reflectionPrompt: 'What surprised you?',
    tags: ['floor', 'flow', 'play', 'yoga-adjacent'],
  },
  {
    id: 'strength-hold',
    name: 'Strength-Control Hold',
    cue: 'Find the hardest position you can sustain. Stay there. Be curious about the shaking.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'Where did your mind go when it got hard?',
    tags: ['strength', 'control', 'presence', 'body-weight'],
  },
  {
    id: 'soft-rolling',
    name: 'Soft Rolling',
    cue: 'Let the body roll — spine, shoulders, hips. Land softly. Make no sound.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'Which side felt different?',
    tags: ['floor', 'play', 'acrobatics', 'soft'],
  },
  {
    id: 'mobility-flow',
    name: 'Mobility Flow',
    cue: 'Move every joint. Go to the end ranges — slowly. The edge is where you actually live.',
    domain: 'physical',
    volume: 'medium',
    durationSeconds: 600,
    reflectionPrompt: 'What felt more open than yesterday?',
    tags: ['mobility', 'joints', 'warm-up', 'foundational'],
  },
  {
    id: 'precision-walk',
    name: 'Precision Walking',
    cue: 'Each step placed with full intention. Slow down until every footfall is a decision.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What changed when you slowed down?',
    tags: ['gait', 'precision', 'presence', 'movement-culture'],
  },
  {
    id: 'hanging',
    name: 'Passive Hang',
    cue: 'Find something overhead. Let the spine decompress. Breathe into the length.',
    domain: 'physical',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'What released?',
    tags: ['decompression', 'spine', 'passive', 'micro'],
  },
  {
    id: 'locomotion-session',
    name: 'Locomotion Session',
    cue: 'Move through space. Every mode of travel is available. Don\'t repeat yourself.',
    domain: 'physical',
    volume: 'long',
    durationSeconds: 1200,
    reflectionPrompt: 'What mode felt most natural today?',
    tags: ['locomotion', 'play', 'exploration', 'weekly'],
  },
  {
    id: 'balance-challenge',
    name: 'Balance Work',
    cue: 'Find your single-leg edge. Stay at the threshold — the wobble is the work.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'Left or right — which one is hiding something?',
    tags: ['balance', 'single-leg', 'coordination', 'precision'],
  },
  {
    id: 'handstand-wall',
    name: 'Handstand Wall Practice',
    cue: 'Walk up the wall. Find vertical. The wall is honest — it won\'t let you pretend.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'Where were you holding tension?',
    tags: ['inversion', 'strength', 'control', 'body-weight'],
  },
  {
    id: 'surf-flow',
    name: 'Surf Flow',
    cue: 'Imagine a wave arriving. Let your hips drop and shift — meet it, don\'t fight it.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'Did you feel the imagined water?',
    tags: ['surfing', 'hip-mobility', 'visualization', 'play'],
  },
  {
    id: 'basketball-footwork',
    name: 'Basketball Footwork',
    cue: 'Solo on defense. React to nothing — plant, pivot, push. Do it slowly first, then let it accelerate.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'Which direction felt lazier?',
    tags: ['basketball', 'footwork', 'coordination', 'play'],
  },

  // ─── MENTAL ─────────────────────────────────────────────────────────────────

  {
    id: 'body-scan',
    name: 'Body Scan',
    cue: 'Start at the soles. Move up slowly. Don\'t change anything — just notice what\'s already there.',
    domain: 'mental',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'What area asked for attention?',
    tags: ['awareness', 'presence', 'scan', 'adhd-friendly'],
  },
  {
    id: 'peripheral-vision',
    name: 'Peripheral Vision',
    cue: 'Soften your gaze. Let the edges of your vision expand. See without looking.',
    domain: 'mental',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'What appeared in the periphery?',
    tags: ['awareness', 'vision', 'presence', 'micro'],
  },
  {
    id: 'slow-motion-awareness',
    name: 'Slow Motion',
    cue: 'Do something ordinary — pouring water, walking to the door — at half speed. Then half again.',
    domain: 'mental',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What detail had you never noticed?',
    tags: ['presence', 'slow', 'awareness', 'movement-culture'],
  },
  {
    id: 'proprioception',
    name: 'Proprioception Focus',
    cue: 'Close your eyes. Feel where you are in space — every joint angle, every point of contact.',
    domain: 'mental',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'Did the body match what you imagined?',
    tags: ['proprioception', 'awareness', 'eyes-closed', 'micro'],
  },
  {
    id: 'movement-visualization',
    name: 'Movement Visualization',
    cue: 'Pick one movement you want. Close your eyes. Do it perfectly — only in your mind.',
    domain: 'mental',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'What detail was hardest to hold clearly?',
    tags: ['visualization', 'mental-rehearsal', 'skill', 'awareness'],
  },
  {
    id: 'count-steps',
    name: 'Mindful Walk',
    cue: 'Walk anywhere. Count each step silently. When you lose count — that\'s the practice.',
    domain: 'mental',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'How far did you get before drifting?',
    tags: ['walking', 'focus', 'adhd-friendly', 'outdoor'],
  },
  {
    id: 'single-focus',
    name: 'Single Object Focus',
    cue: 'Choose one thing in the room. Give it your full, undivided attention for the whole time.',
    domain: 'mental',
    volume: 'micro',
    durationSeconds: 60,
    reflectionPrompt: 'When did the mind try to leave?',
    tags: ['focus', 'attention', 'adhd-friendly', 'micro'],
  },

  // ─── SPIRITUAL ───────────────────────────────────────────────────────────────

  {
    id: 'stillness',
    name: '30 Seconds of Stillness',
    cue: 'Stand or sit. Don\'t adjust. Let the body be exactly as it is.',
    domain: 'spiritual',
    volume: 'micro',
    durationSeconds: 30,
    reflectionPrompt: 'What was the first urge to move?',
    tags: ['stillness', 'micro', 'presence', 'foundational'],
  },
  {
    id: 'breath-ritual',
    name: 'Breath Ritual',
    cue: 'Inhale for four. Hold for four. Exhale for eight. This is the whole practice.',
    domain: 'spiritual',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'Where did the breath land in the body?',
    tags: ['breath', 'nervous-system', 'calm', 'sleep-prep'],
  },
  {
    id: 'last-rep',
    name: 'Last Rep Reflection',
    cue: 'What was today? Not what you did — what you actually experienced.',
    domain: 'spiritual',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'One word for the session.',
    tags: ['reflection', 'integration', 'evening', 'journal'],
  },
  {
    id: 'stillness-sit',
    name: 'Stillness Sit',
    cue: 'Sit comfortably. The practice is simply staying — and noticing when you want to leave.',
    domain: 'spiritual',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'How many times did you almost get up?',
    tags: ['stillness', 'meditation', 'presence', 'evening'],
  },
  {
    id: 'body-listening',
    name: 'Body Listening',
    cue: 'Ask the body what it wants — not what you think it needs. Then actually listen.',
    domain: 'spiritual',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'What did it say?',
    tags: ['intuition', 'awareness', 'nervous-system', 'rest'],
  },
  {
    id: 'exhale-practice',
    name: 'Slow Exhale',
    cue: 'One breath: inhale normally. Exhale as slowly as you possibly can. One time is enough.',
    domain: 'spiritual',
    volume: 'micro',
    durationSeconds: 60,
    reflectionPrompt: 'What shifted?',
    tags: ['breath', 'micro', 'state-shift', 'adhd-friendly'],
  },
  {
    id: 'gratitude-motion',
    name: 'Gratitude in Motion',
    cue: 'Move in a way that says thank you — to no one specific. Let the body express it.',
    domain: 'spiritual',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'What were you grateful for without knowing it?',
    tags: ['gratitude', 'movement', 'spiritual', 'expressive'],
  },
  {
    id: 'nature-connection',
    name: 'Nature Connection',
    cue: 'Go outside. Find one thing living — a tree, grass, the sky. Give it five minutes of real attention.',
    domain: 'spiritual',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What did it teach you?',
    tags: ['nature', 'outdoor', 'presence', 'yaar-hashirim'],
  },

  // ─── CREATIVE ────────────────────────────────────────────────────────────────

  {
    id: 'improv-movement',
    name: 'Improvised Movement',
    cue: 'No goal, no style, no correct answer. Move until something honest comes out.',
    domain: 'creative',
    volume: 'medium',
    durationSeconds: 600,
    reflectionPrompt: 'What emerged that you didn\'t plan?',
    tags: ['improvisation', 'play', 'movement-culture', 'ido-portal'],
  },
  {
    id: 'movement-to-music',
    name: 'Movement to Music',
    cue: 'Put on one track. Let the music move you — you\'re not dancing, you\'re translating.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What did the music ask your body to do?',
    tags: ['music', 'movement', 'djing', 'rhythm', 'play'],
  },
  {
    id: 'word-to-movement',
    name: 'Word → Movement',
    cue: 'The word is: WEIGHT. Don\'t think about it — let the body respond to it.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'Did the word change meaning through the body?',
    tags: ['creative', 'expressive', 'word', 'improvisation'],
  },
  {
    id: 'invent-drill',
    name: 'Invent a Drill',
    cue: 'Create one movement challenge that doesn\'t exist yet. Then try to do it.',
    domain: 'creative',
    volume: 'medium',
    durationSeconds: 600,
    reflectionPrompt: 'What was the drill you invented?',
    tags: ['creativity', 'play', 'invention', 'movement-culture'],
  },
  {
    id: 'soft-acrobatics',
    name: 'Soft Acrobatics',
    cue: 'Play with falling. Play with height. No perfection required — just curiosity.',
    domain: 'creative',
    volume: 'long',
    durationSeconds: 900,
    reflectionPrompt: 'What fear appeared?',
    tags: ['acrobatics', 'play', 'floor', 'exploration', 'weekly'],
  },
  {
    id: 'draw-what-you-feel',
    name: 'Draw What You Feel',
    cue: 'Get something to draw with. No representation — just lines, pressure, shapes that match your body state.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What color was the session?',
    tags: ['drawing', 'collage', 'creative', 'reflection', 'art'],
  },
  {
    id: 'rhythm-body',
    name: 'Body Percussion',
    cue: 'Your body is the instrument. Find a rhythm with your hands, feet, chest. Build it. Then break it.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What rhythm wanted to stay?',
    tags: ['music', 'rhythm', 'djing', 'percussion', 'play'],
  },
  {
    id: 'locomotion-improv',
    name: 'Locomotion Improvisation',
    cue: 'Travel through space as if you\'ve never moved before. Every option is new.',
    domain: 'creative',
    volume: 'long',
    durationSeconds: 1200,
    reflectionPrompt: 'What mode of travel felt most alive?',
    tags: ['locomotion', 'improvisation', 'play', 'weekly'],
  },

  // ─── MUSIC ──────────────────────────────────────────────────────────────────

  {
    id: 'listen-full-body',
    name: 'Full Body Listening',
    cue: 'Put something on. Close your eyes. Don\'t analyze — just feel where the sound lands in you.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'Where did the music live in your body?',
    tags: ['music', 'listening', 'sound', 'presence', 'djing'],
  },
  {
    id: 'hum-meditation',
    name: 'Hum Resonance',
    cue: 'Find a tone in your chest. Let it out — low, sustained. Feel the vibration move.',
    domain: 'spiritual',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'Where did the hum want to go?',
    tags: ['music', 'sound', 'breath', 'resonance', 'voice'],
  },
  {
    id: 'rhythm-walk',
    name: 'Rhythm Walk',
    cue: 'Find a beat in your head. Let your footsteps lock into it. Don\'t force — follow.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'Did the rhythm change you, or did you change it?',
    tags: ['music', 'rhythm', 'walking', 'djing', 'outdoor'],
  },
  {
    id: 'compose-silence',
    name: 'Compose in Silence',
    cue: 'Build a track in your head. Hear every element. Don\'t rush to the drop.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What was the best part of it?',
    tags: ['music', 'djing', 'composition', 'mental', 'creative'],
  },
  {
    id: 'listen-draw',
    name: 'Listen & Draw',
    cue: 'Music on. Pen moving. Don\'t draw anything — just let the sound become marks.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What did the music look like?',
    tags: ['music', 'drawing', 'art', 'creative', 'listening'],
  },
  {
    id: 'vocal-movement',
    name: 'Voice & Movement',
    cue: 'Make a sound. Let that sound move your body. Follow the impulse without thinking.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'Which came first — the sound or the movement?',
    tags: ['music', 'voice', 'movement', 'improvisation', 'expressive'],
  },

  // ─── ART ────────────────────────────────────────────────────────────────────

  {
    id: 'five-min-sketch',
    name: '5-Minute Sketch',
    cue: 'Draw something in front of you. Don\'t lift the pen. Speed matters less than continuity.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What did the hand know that the eye didn\'t?',
    tags: ['drawing', 'art', 'sketch', 'creative', 'visual'],
  },
  {
    id: 'color-observation',
    name: 'Color Sit',
    cue: 'Find one color in the room. Stare at it. Let it fill your field of vision completely.',
    domain: 'mental',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'Did the color change?',
    tags: ['art', 'visual', 'attention', 'awareness', 'color'],
  },
  {
    id: 'air-drawing',
    name: 'Draw in Air',
    cue: 'Use your whole arm — big gestures. Draw something imaginary at room scale.',
    domain: 'creative',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'What did you draw?',
    tags: ['drawing', 'art', 'movement', 'creative', 'expressive'],
  },
  {
    id: 'collage-vision',
    name: 'Mental Collage',
    cue: 'Close your eyes. Assemble images — textures, colors, faces, places. Let it become something.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'What was the center of it?',
    tags: ['collage', 'art', 'visualization', 'creative', 'drawing'],
  },
  {
    id: 'texture-walk',
    name: 'Texture Awareness',
    cue: 'Move through the space touching surfaces. Slow down. Every texture is different information.',
    domain: 'mental',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'Which texture surprised you?',
    tags: ['art', 'tactile', 'awareness', 'sensory', 'presence'],
  },

  // ─── WRITING ─────────────────────────────────────────────────────────────────

  {
    id: 'morning-pages',
    name: 'Free Write',
    cue: 'Write without stopping. Don\'t edit, don\'t think. Just let the hand move until the time ends.',
    domain: 'creative',
    volume: 'short',
    durationSeconds: 180,
    reflectionPrompt: 'What came out that surprised you?',
    tags: ['writing', 'journal', 'creative', 'reflection', 'morning'],
  },
  {
    id: 'one-true-sentence',
    name: 'One True Sentence',
    cue: 'Write the most honest sentence you can about right now. Just one.',
    domain: 'creative',
    volume: 'micro',
    durationSeconds: 60,
    reflectionPrompt: 'Was it true?',
    tags: ['writing', 'journal', 'micro', 'presence', 'reflection'],
  },
  {
    id: 'body-to-word',
    name: 'Body → Word',
    cue: 'Scan your body. Find the sensation that\'s most present. Write it — not as metaphor, as fact.',
    domain: 'spiritual',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'Did the word fit?',
    tags: ['writing', 'body-scan', 'awareness', 'integration', 'spiritual'],
  },
  {
    id: 'unsent-letter',
    name: 'Unsent Letter',
    cue: 'Write to someone or something. You won\'t send it. That\'s the point.',
    domain: 'creative',
    volume: 'medium',
    durationSeconds: 600,
    reflectionPrompt: 'What couldn\'t you say out loud?',
    tags: ['writing', 'creative', 'emotional', 'journal', 'deep'],
  },

  // ─── OUTDOOR ─────────────────────────────────────────────────────────────────

  {
    id: 'barefoot-ground',
    name: 'Barefoot Contact',
    cue: 'Take your shoes off. Stand on the ground. Feel everything it\'s telling you.',
    domain: 'spiritual',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'What did the ground feel like?',
    tags: ['outdoor', 'barefoot', 'nature', 'grounding', 'spiritual'],
  },
  {
    id: 'tree-locomotion',
    name: 'Tree Locomotion',
    cue: 'Find trees. Move between them, around them, under them. Let the terrain decide.',
    domain: 'physical',
    volume: 'medium',
    durationSeconds: 600,
    reflectionPrompt: 'What did the environment ask for?',
    tags: ['outdoor', 'nature', 'locomotion', 'play', 'yaar-hashirim'],
  },
  {
    id: 'cloud-watch',
    name: 'Cloud Watching',
    cue: 'Lie on your back. Watch the sky without naming anything. Just let it move.',
    domain: 'spiritual',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'How long until the mind went quiet?',
    tags: ['outdoor', 'nature', 'stillness', 'sky', 'rest'],
  },
  {
    id: 'sensory-map',
    name: 'Sensory Mapping',
    cue: 'Name 5 sounds. 4 things you can touch. 3 things you can see. 2 smells. 1 taste.',
    domain: 'mental',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'Which sense was hardest to find?',
    tags: ['outdoor', 'sensory', 'presence', 'adhd-friendly', 'awareness'],
  },
  {
    id: 'sprint-stop',
    name: 'Sprint & Stop',
    cue: 'Sprint hard for 5 seconds. Stop completely. Feel everything. Repeat when ready.',
    domain: 'physical',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What did your body do in the stillness after?',
    tags: ['outdoor', 'sprint', 'physical', 'energy', 'play'],
  },

  // ─── STATE-SPECIFIC ──────────────────────────────────────────────────────────

  {
    id: 'anxiety-breath',
    name: 'Anchor Breath',
    cue: 'Both feet on the floor. One hand on chest. Breathe until you feel the floor through your feet.',
    domain: 'spiritual',
    volume: 'micro',
    durationSeconds: 90,
    reflectionPrompt: 'Did the body soften?',
    tags: ['breath', 'anxious', 'nervous-system', 'calm', 'grounding', 'adhd-friendly'],
  },
  {
    id: 'tired-wave',
    name: 'Tired Body Wave',
    cue: 'You don\'t need to do anything. Just let the spine undulate — one slow wave. Then another.',
    domain: 'physical',
    volume: 'micro',
    durationSeconds: 120,
    reflectionPrompt: 'Did you find anything in the tiredness?',
    tags: ['tired', 'gentle', 'passive', 'spine', 'micro'],
  },
  {
    id: 'scattered-ground',
    name: 'Ground Yourself',
    cue: 'Sit or stand. Name where you are out loud — room, city, country. Then feel your weight.',
    domain: 'mental',
    volume: 'micro',
    durationSeconds: 60,
    reflectionPrompt: 'Did the scattered feeling move?',
    tags: ['scattered', 'adhd-friendly', 'grounding', 'focus', 'micro'],
  },
  {
    id: 'heavy-floor',
    name: 'Heavy Floor Practice',
    cue: 'Get on the floor. Completely. Let gravity win. Stay there. That\'s all.',
    domain: 'spiritual',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'What did the floor hold for you?',
    tags: ['heavy', 'floor', 'rest', 'gentle', 'gravity', 'spiritual'],
  },
  {
    id: 'restless-shake',
    name: 'Full Body Shake',
    cue: 'Start with your hands. Let it travel up the arms, the torso, the legs. Shake everything loose.',
    domain: 'physical',
    volume: 'micro',
    durationSeconds: 90,
    reflectionPrompt: 'What released?',
    tags: ['restless', 'shake', 'release', 'nervous-system', 'energy'],
  },
  {
    id: 'weed-alternative',
    name: 'State Shift',
    cue: 'You want to change how you feel. Start with one breath. Then one movement. Then follow.',
    domain: 'spiritual',
    volume: 'short',
    durationSeconds: 300,
    reflectionPrompt: 'Did the state shift?',
    tags: ['state-shift', 'breath', 'presence', 'transition', 'nervous-system'],
  },
]

export const domainColors: Record<Domain, string> = {
  physical: '#C4862A',
  mental: '#5B7FA6',
  spiritual: '#6B9E7A',
  creative: '#A6607A',
}

export const domainLabels: Record<Domain, string> = {
  physical: 'Physical',
  mental: 'Mental',
  spiritual: 'Spiritual',
  creative: 'Creative',
}
